"""
报告生成器 - 多种输出格式支持
"""
import json
from datetime import datetime
from pathlib import Path
from typing import Any, List

from core.analyzer import ScanResult, Vulnerability, Severity


class ReportGenerator:
    """报告生成器"""

    def __init__(self, result: ScanResult):
        self.result = result

    def to_json(self, pretty: bool = True) -> str:
        """生成 JSON 格式报告"""
        data = self._build_report_data()
        if pretty:
            return json.dumps(data, indent=2, ensure_ascii=False)
        return json.dumps(data, ensure_ascii=False)

    def to_text(self, verbose: bool = False) -> str:
        """生成人类可读的文本报告"""
        lines = [
            "=" * 60,
            "🔒 CodeSentry 安全扫描报告",
            "=" * 60,
            f"📂 目标: {self.result.target}",
            f"📊 文件数: {self.result.total_files}",
            f"📝 代码行数: {self.result.total_lines}",
            f"⏱️  扫描耗时: {self.result.scan_time_seconds:.2f}秒",
            "",
            "📈 漏洞统计:",
            f"  🔴 Critical: {self.result.critical_count}",
            f"  🟠 High: {self.result.high_count}",
            f"  🟡 Medium: {self.result.medium_count}",
            f"  🟢 Low: {self.result.low_count}",
            "",
        ]

        if self.result.vulnerabilities:
            severity_order = [
                Severity.CRITICAL, Severity.HIGH,
                Severity.MEDIUM, Severity.LOW, Severity.INFO
            ]

            for severity in severity_order:
                vulns = [v for v in self.result.vulnerabilities if v.severity == severity]
                if not vulns:
                    continue

                icon = {
                    Severity.CRITICAL: "🔴",
                    Severity.HIGH: "🟠",
                    Severity.MEDIUM: "🟡",
                    Severity.LOW: "🟢",
                    Severity.INFO: "🔵",
                }[severity]

                lines.append(f"\n{icon} {severity.value.upper()} 漏洞 ({len(vulns)}):")
                lines.append("-" * 60)

                for i, vuln in enumerate(vulns, 1):
                    lines.append(f"\n{i}. {vuln.title}")
                    lines.append(f"   📍 位置: {vuln.location}")
                    lines.append(f"   🏷️  类型: {vuln.type.value} ({vuln.cwe_id})")
                    lines.append(f"   🎯 置信度: {vuln.confidence:.0%}")

                    if vuln.ai_verified:
                        lines.append(f"   ✅ AI 验证: 已确认")

                    if vuln.ai_analysis:
                        lines.append(f"   📝 AI 分析: {vuln.ai_analysis}")

                    if vuln.fix_suggestion:
                        lines.append(f"   💡 修复建议: {vuln.fix_suggestion}")

                    lines.append("```")
                    lines.append(vuln.code_snippet)
                    lines.append("```")

        if self.result.errors:
            lines.extend([
                "",
                "⚠️ 扫描过程中的错误:",
                "\n".join(f"  - {e}" for e in self.result.errors[:10]),
            ])

        lines.extend([
            "",
            "=" * 60,
            f"报告生成时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "Generated by CodeSentry - AI-Powered Code Security Auditor",
            "=" * 60,
        ])

        return "\n".join(lines)

    def _build_report_data(self) -> dict[str, Any]:
        """构建报告数据"""
        return {
            "scan_info": {
                "target": self.result.target,
                "timestamp": datetime.now().isoformat(),
                "total_files": self.result.total_files,
                "total_lines": self.result.total_lines,
                "scan_time_seconds": self.result.scan_time_seconds,
            },
            "statistics": {
                "critical": self.result.critical_count,
                "high": self.result.high_count,
                "medium": self.result.medium_count,
                "low": self.result.low_count,
                "total": len(self.result.vulnerabilities),
            },
            "vulnerabilities": [
                {
                    "id": v.id,
                    "type": v.type.name,
                    "severity": v.severity.value,
                    "title": v.title,
                    "description": v.description,
                    "location": {
                        "file": v.location.file,
                        "line": v.location.line,
                    },
                    "cwe_id": v.cwe_id,
                    "confidence": v.confidence,
                    "ai_verified": v.ai_verified,
                    "ai_analysis": v.ai_analysis,
                    "ai_verification_result": v.ai_verification_result,
                    "fix_suggestion": v.fix_suggestion,
                    "code_snippet": v.code_snippet,
                }
                for v in self.result.vulnerabilities
            ],
            "errors": self.result.errors,
        }

    def save(self, output_path: str, format: str = "text"):
        """保存报告到文件"""
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)

        if format == "json":
            content = self.to_json()
        else:
            content = self.to_text()

        with open(path, "w", encoding="utf-8") as f:
            f.write(content)

        print(f"✅ 报告已保存到: {output_path}")
        return path
